server:
  port: 8080
  servlet:
    context-path: /reconciliation

scheduling: true

maas:
  data-directory: ./resources/data/
  deleted-directory: ${maas.data-directory}/deleted
  fileSystemDataSets: 1000-bank-transaction-records.csv,1000-bank-transaction-records-mission.csv

logging:
  config: classpath:logback.xml